apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 5000  
    protocol: TCP
  selector:
    app: sample-app



