apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer   # Change this from NodePort to LoadBalancer
  ports:
  - name: http
    port: 8081          # The port exposed by the load balancer
    targetPort: 3000    # The port on your container
    protocol: TCP
  selector:
    app: sample-app




