apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443           # Externally exposed port (HTTPS)
      targetPort: 3000    # Your app listens on this inside the pod
      protocol: TCP
  selector:
    app: sample-app       # Make sure this matches your Deployment label





