apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer             # This provisions an AWS NLB (or ALB via controller)
  ports:
    - name: http
      port: 8081                  # Clients access on this port (externally)
      targetPort: 3000           # This must match the port your app listens to inside the pod
      protocol: TCP
  selector:
    app: sample-app              # Matches pods with label "app: sample-app"

   # Make sure this matches your Deployment label





