apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081         # Internal port
      targetPort: 3000   # The port on your container
      protocol: TCP
    - name: https
      port: 443          # Exposed as HTTPS on the LoadBalancer
      targetPort: 3000   # Port to route to inside the container
      protocol: TCP
  selector:
    app: sample-app
   # Make sure this matches your Deployment label





